### PR TITLE
Add percy inside bors.toml file

### LINKED ISSUE #505: Add `percy` inside `bors.toml` file
Currently, `bors` only checks the statuses of the `linter_check` and `cypress-run` tests.
We want to add also the `percy` test, as it is a requirement before merging a PR.

### PR DESCRIPTION
**Pull request by developer-diganta**
# Pull Request

## Related issue
Fixes #505 

## What does this PR do?
- I have added percy to bors.toml

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Review by mdubus — APPROVED** [review]
LGTM 🚀 🥳

Thanks a lot for your PR!

**Comment by mdubus** [comment]
bors try

**Comment by developer-diganta** [comment]
@mdubus Hi! I had already filled the form once before with another PR. Shall I fill it again?

**Comment by developer-diganta** [comment]
@mdubus Thank You for confirming!

**Pull request merged**
