### PR TITLE
removed every mentions of npm in contributing markdown

### LINKED ISSUE #496: Remove `npm` mentions in Contributing guide.
In the contributing guide we are suggesting to either start the project with `npm` or `yarn`. 
Since we are using a `yarn.lock`, by using `npm` we are not using the fixed packages versions with which we know the project runs in the expected way. 

Thus, `npm` should not be suggested. Only yarn.

### PR DESCRIPTION
**Pull request by joanjeremiah**
# Pull Request

## Related issue
Fixes #496
## What does this PR do?
- The PR has made changes in CONTRIBUTING.md markdown and has removed all mentions of 'npm' in it.

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Comment by joanjeremiah** [comment]
> Hey @joanjeremiah thanks a lot for your contribution 🙏
> 
> could you improve the body of your PR?

I have improved the body of PR.

**Comment by bidoubiwa** [comment]
Thanks a lot! 

We will wait on the return of @mdubus to merge it, which comes back on Monday I think. Meanwhile I tag this as `hacktoberst-accepted`, it should work as a contribution of digital ocean

**Comment by joanjeremiah** [comment]
> Thanks a lot!
> 
> We will wait on the return of @mdubus to merge it, which comes back on Monday I think. Meanwhile I tag this as `hacktoberst-accepted`, it should work as a contribution of digital ocean

Thank you

**Comment by bidoubiwa** [comment]
Oh by the way! 
If you are participating in [Hacktoberfest](https://blog.meilisearch.com/contribute-hacktoberfest-2022/), and you would like to receive a small gift from Meilisearch too, don't forget to fill [this form](https://meilisearch.typeform.com/to/idt5qugY).

**Comment by mdubus** [comment]
Hello @joanjeremiah  👋 

Thanks a lot for your PR, and @bidoubiwa for the review! This looks good to me 🤩

bors try

**Comment by bidoubiwa** [comment]
_This message is sent automatically_

Thanks again for contributing to Meilisearch :heart:
If you are participating in [Hacktoberfest](https://blog.meilisearch.com/contribute-hacktoberfest-2022/), and you would like to receive some gift from Meilisearch too, please complete [this form](https://meilisearch.typeform.com/to/idt5qugY).

**Pull request merged**
