### PR TITLE
Transform getHomepageData function into homepageData object

### LINKED ISSUE #546: Transform `getHomepageData` function into `homepageData` object
We currently have every text of the website inside the `data` folder, separated in different files.

The one for the homepage is the `data/homepage.js`. It exports a function called `getHomepageData` which doesn't receive any argument. This is legacy code, and we would like to rework it in order to have an object instead. 

What we have to do is: 
- Transform the `getHomepageData`  function of the `data/homepage.js` file into an object
- Rename `getHomepageData` into `homepageData` in every file that uses it (including the `stories` folder used by Storybook)

### PR DESCRIPTION
**Pull request by FilipePfluck**
# Pull Request

## Related issue
Fixes #546

## What does this PR do?
- Transform the ```getHomepageData``` function of the ```data/homepage.js``` file into an object
- Rename ```getHomepageData``` into ```homepageData``` in every file that uses it 

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Comment by FilipePfluck** [comment]
Hey @mdubus I made the PR

**Comment by mdubus** [comment]
Hi @FilipePfluck 👋 

Thanks a lot for the PR 🙏 Did you manage to make to project run? It's working on my side being on your branch, but don't hesitate to ask if you have still a problem with it 😊

**Comment by FilipePfluck** [comment]
> Hi @FilipePfluck wave
> 
> Thanks a lot for the PR pray Did you manage to make to project run? It's working on my side being on your branch, but don't hesitate to ask if you still have a problem with it blush

Yes, I installed yarn and used it, and now the project is running properly!

**Review by mdubus — APPROVED** [review]
That's perfect, thanks a lot ! 

Other issues like this one are coming, stay tuned if you want to contribute to some of them 😉

Edit: An other issue like this one has been created here: #551

bors merge

**Pull request merged**
